### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alehuo** [TKOaly/user-service#62]
- [ ] Convert seed and migration files to TypeScript
- [ ] Improve model validation
- [ ] Configure Knex to return timestamps as strings
- [ ] Configure Knex for correct charset & timezone
